---

- name: update ca store
  ansible.builtin.command:
    cmd: "/usr/sbin/update-ca-certificates"
  changed_when: true

- name: restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted
  changed_when: true
  ignore_errors: "{{ ansible_check_mode }}"

